### ISSUE TITLE
Refactor limesurvey_release_link

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/limesurvey#2]
Just something like `limesurvey_version`

**Comment by Scriptkiddi** [comment]
not sure if i can work with that `https://github.com/LimeSurvey/LimeSurvey/archive/2.72.4+171110.tar.gz`
would the version include the release date like `2.72.4+171110` or just `2.72.4`?

**Comment by dasJ** [comment]
Both ofc

**Comment by ghost** [comment]
+1

**Comment by jleaders** [comment]
Please also add supported versions

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 92 days.
